version: 2
servies:
    wordpress1:
        image: wordpress
        ports:
            - 9001:80
        network:
            network1
    
    Wordpress2:
        image: wordpress
        ports:
            - 9002:80
        network:
             network1
    ng1:
        image: nginx
        ports: 
            - 80:80
        network:
             network1
networks:
    network1
        
