version: '3'

services:
  web1:
    build: .
    command: gunicorn --bind :8001 --workers 3 core.wsgi
    volumes:
      - .:/code
    expose:
      - 8001
    env_file:
      - .env
    depends_on:
      - db
  web2:
    build: .
    command: gunicorn --bind :8002 --workers 3 core.wsgi
    volumes:
      - .:/code
    expose:
      - 8002
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: homelist_db
      POSTGRES_USER: homelist_user
      POSTGRES_PASSWORD: homelist_password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
  
##Itsalirez
